### PR TITLE
Prevent click in menu going outside of the menu

### PR DESCRIPTION
**Pull request by yEsPaP**

### CODE REVIEW

**Comment by ama6nen** [comment]
Pretty sure typing with menu open / etc is also still messed up in this public version too

**Comment by yEsPaP** [comment]
> Pretty sure typing with menu open / etc is also still messed up in this public version too

its not for me i think

**Comment by GoodPog** [comment]
it feels more broken tbh

**Comment by yEsPaP** [comment]
> it feels more broken tbh

whats wrong? can you send video

**Pull request merged**
