### PR TITLE
/warp

### PR DESCRIPTION
**Pull request by qatroxx**
isn't this easier? @Cytee

### CODE REVIEW

**Comment by Cytee** [comment]
> isn't this easier? @Cytee

yeah its an easier.

**Comment by iRestartz** [comment]
what about write ``asdasd /warp start`` in input?

**Comment by Cytee** [comment]
> what about write `asdasd /warp start` in input?

nope just write `/warp worldname`

**Comment by iRestartz** [comment]
> > what about write `asdasd /warp start` in input?
> 
> nope just write `/warp worldname`

i mean you can do whatever  ``/warp worldname`` or ``asdasd /warp worldname`` with that code

**Comment by qatroxx** [comment]
https://prnt.sc/15uxowz u can do any shit, even (          /warp 123)

**Pull request merged**
